### ISSUE TITLE
default implementation?

### ISSUE THREAD

**Issue by matthiasdebernardini** [0xtlt/lnbits_rust#4]
How do you feel about adding a default implementation that connects to the legend server and sends to a known wallet. 

Would be great for prototyping, granted setting up lnbits is so easy but eliminating one more step would be good IMO.

Thoughts?

**Comment by f321x** [comment]
IMO adding a default server is not a good idea as some will probably use it for more than testing. Looking at what happened to legend (hacked) this can end badly. A dev using this crate is able to run a lnbits instance (or copy a string from somewhere)
